### ISSUE TITLE
Midrub removal

### ISSUE THREAD

**Issue by AKprisonER** [scrisoft/midrub_cms#10]
Hi,

Why was Midrub removed from Codecanyon?
Does it had any bugs or security issues? Also do u have plans to update midrub regularly?

**Comment by scrisoft** [comment]
Hi,

I'm working on the most advanced social posting app and will be released in september.

But before this, i'm working now to upgrade the Midrub CMS to CodeIgniter 4. 

Midrub CMS is only a platform where are installed the apps.

**Comment by AKprisonER** [comment]
But will this available again In Codecanyon?

**Comment by AKprisonER** [comment]
Also any demo for the new posting app?

**Comment by scrisoft** [comment]
Yes. 

In a month will be clear why i have removed the old items when the people will see the quality.

Now the big problem is to upgrade CodeIgniter because requires a lot of attention.

There are some videos in my Youtube channels with the new posting app, but i prefer to not show for now the composer. Ițm going to register first the copyright.

**Comment by AKprisonER** [comment]
That will be great. Hope the same features such as medium, Telegram remains in this new version too.
If possible, add discord functions too since many people are using it and there is no service that offers discord features.

**Comment by scrisoft** [comment]
The new posting app has universal features which could be used even to create products on shops.

**Comment by AKprisonER** [comment]
What will happen to midrub 0.08.5, can users update this to the new version that you will be launching in a month?

**Comment by scrisoft** [comment]
Will be required reinstallation.
